package:
  name: irpy
  version: 0.4

requirements:
  build:
    - python 2.7*
    - setuptools
  run:
    - python 2.7*

source:
  git_url: https://github.com/TApplencourt/IRPy.git

about:
  summary: IRP for Python
  license_file: LICENSE