package:
  name: irpy
  version: 0.1

requirements:
  build:
    - python
    - setuptools
  run:
    - python

source:
  git_url: https://github.com/TApplencourt/IRPy.git

about:
  summary: IRP for Python
  license_file: LICENSE